version: '3.8'

services:
  frontend:
    build:
      context: ./apps/frontend-nextjs
      dockerfile: /docker/dev.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
  backend:
    build:
      context: ./apps/backend-spring
      dockerfile: Dockerfile
    ports:
      - "8080:8080"